/** Sample conversation data for the simulation. */

export type Agent = Readonly<{ name: string; icon: string; color: string }>;

export type ConversationEvent = Readonly<
  | { type: "delegation"; from: string; to: string; task: string }
  | { type: "response"; agent: string; output: string }
>;

export const agents: Readonly<Record<string, Agent>> = {
  orchestrator: { name: "orchestrator", icon: "🤖", color: "#72f1b8" },
  "eng-lead": { name: "eng-lead", icon: "🔧", color: "#ff6e96" },
  "frontend-dev": { name: "frontend-dev", icon: "💻", color: "#36f9f6" },
  "backend-dev": { name: "backend-dev", icon: "💻", color: "#ff7edb" },
  "validation-lead": { name: "validation-lead", icon: "🛡", color: "#ff9e64" },
  "qa-engineer": { name: "qa-engineer", icon: "🧪", color: "#7dcfff" },
  "security-rev": { name: "security-rev", icon: "🔒", color: "#bb9af7" },
};

export const conversation: ReadonlyArray<ConversationEvent> = [
  {
    type: "delegation",
    from: "orchestrator",
    to: "eng-lead",
    task: [
      "Build feature X: add proper error handling across the frontend error dialog and backend API error responses.",
      "",
      "Requirements:",
      "- Frontend needs a reusable ErrorDialog component with support for network, validation, and unknown error states",
      "- Backend API endpoints (/api/users, /api/posts) must return structured ErrorResponse objects",
      "- Both sides must share the same error code enum so the frontend can map codes to UI states",
      "- Use the existing Modal component as the base for the dialog",
    ].join("\n"),
  },
  {
    type: "delegation",
    from: "eng-lead",
    to: "frontend-dev",
    task: [
      "Build the UI components for the error dialog. Here's what I need:",
      "",
      "1. ErrorDialog.tsx — a modal dialog that accepts an `errorCode` prop and renders the appropriate state:",
      "   - NETWORK_ERROR: 'Connection failed' with a retry button",
      "   - VALIDATION_ERROR: 'Invalid input' with field-level error highlights",
      "   - UNKNOWN_ERROR: generic 'Something went wrong' with a support link",
      "2. ErrorBoundary.tsx — a React error boundary that catches render errors and shows the ErrorDialog",
      "3. Use the existing Modal component from src/components/Modal.tsx as the base",
      "",
      "The error codes are defined in shared/types.ts — import them from there.",
    ].join("\n"),
  },
  {
    type: "response",
    agent: "frontend-dev",
    output: [
      "Done. Created three files:",
      "",
      "**src/components/ErrorDialog.tsx**",
      "- Accepts `errorCode: ErrorCode` and `onRetry?: () => void` props",
      "- Renders different content per error state using a switch on the code",
      "- NETWORK_ERROR shows retry button that calls `onRetry`",
      "- VALIDATION_ERROR accepts optional `fieldErrors: Record<string, string>` and highlights them",
      "- UNKNOWN_ERROR shows a mailto: link to support@company.com",
      "- All states share the same Modal wrapper with consistent close behavior",
      "",
      "**src/components/ErrorBoundary.tsx**",
      "- Wraps children in a class-based error boundary (React requirement)",
      "- Catches render errors and displays ErrorDialog with UNKNOWN_ERROR",
      "- Includes a 'Try again' button that resets the boundary state",
      "",
      "**src/styles/error.css**",
      "- Slide-in animation for the dialog (200ms ease-out)",
      "- Shake animation on the retry button for network errors",
      "- Red border highlight for validation field errors",
      "",
      "All components are typed and exported from src/components/index.ts.",
    ].join("\n"),
  },
  {
    type: "delegation",
    from: "eng-lead",
    to: "backend-dev",
    task: [
      "Add structured error response types to the API. Specifically:",
      "",
      "1. Create `ErrorResponse` type in shared/types.ts with fields: `code: ErrorCode`, `message: string`, `details?: Record<string, unknown>`",
      "2. Update /api/users POST handler — return ErrorResponse for:",
      "   - Missing required fields (VALIDATION_ERROR)",
      "   - Database connection failures (NETWORK_ERROR)",
      "   - Unexpected throws (UNKNOWN_ERROR)",
      "3. Update /api/posts POST/PUT handlers — same error handling pattern",
      "4. Add error middleware in src/middleware/error.ts that catches unhandled exceptions and wraps them into ErrorResponse format",
      "",
      "The error codes enum already exists in shared/types.ts — extend it if needed.",
    ].join("\n"),
  },
  {
    type: "response",
    agent: "backend-dev",
    output: [
      "Implemented. Here's what changed:",
      "",
      "**shared/types.ts**",
      "- Added `ErrorResponse` interface: `{ code: ErrorCode; message: string; details?: Record<string, unknown> }`",
      "- ErrorCode enum already had NETWORK_ERROR and UNKNOWN_ERROR, added VALIDATION_ERROR",
      "",
      "**src/routes/users.ts**",
      "- POST handler now validates body with Zod schema, returns `{ code: 'VALIDATION_ERROR', message: 'Invalid input', details: { fields: zodErrors } }` on parse failure",
      "- Wrapped DB calls in try/catch — connection errors return NETWORK_ERROR with the DB host in details (dev only)",
      "",
      "**src/routes/posts.ts**",
      "- Same pattern applied to POST and PUT handlers",
      "- Added input validation for title (min 1 char) and body (min 10 chars)",
      "",
      "**src/middleware/error.ts** (new file)",
      "- Express error middleware that catches any unhandled throw",
      "- In production: returns `{ code: 'UNKNOWN_ERROR', message: 'Internal server error' }` — no stack trace",
      "- In development: includes `details: { stack: err.stack }` for debugging",
      "- All error responses set appropriate HTTP status codes (400, 500, 503)",
    ].join("\n"),
  },
  {
    type: "response",
    agent: "eng-lead",
    output: [
      "Both frontend and backend work is complete. Summary:",
      "",
      "**Frontend (3 files)**",
      "- ErrorDialog component handles all three error states with appropriate UX (retry, field highlights, support link)",
      "- ErrorBoundary catches render crashes and shows the dialog",
      "- CSS animations make the error states feel polished",
      "",
      "**Backend (4 files modified)**",
      "- ErrorResponse type shared between frontend and backend via shared/types.ts",
      "- Both /api/users and /api/posts return structured errors with correct HTTP status codes",
      "- Error middleware catches unhandled exceptions and strips sensitive info in production",
      "",
      "The error codes are the single source of truth in shared/types.ts — both sides import from there, so they can't drift.",
    ].join("\n"),
  },
  {
    type: "delegation",
    from: "orchestrator",
    to: "validation-lead",
    task: [
      "Validate the error handling implementation that Engineering just completed.",
      "",
      "I need you to:",
      "1. Have QA write comprehensive test cases covering all error states on both frontend and backend",
      "2. Have Security review the error responses for information leakage — no stack traces or internal paths in production",
      "",
      "Report back with test results and any security findings.",
    ].join("\n"),
  },
  {
    type: "delegation",
    from: "validation-lead",
    to: "qa-engineer",
    task: [
      "Write test cases for the new error handling. Cover these scenarios:",
      "",
      "**Frontend (ErrorDialog.tsx)**",
      "- Renders correct message for NETWORK_ERROR, VALIDATION_ERROR, UNKNOWN_ERROR",
      "- Retry button appears only for NETWORK_ERROR and calls onRetry",
      "- Field errors render when VALIDATION_ERROR includes fieldErrors prop",
      "- Unknown/unexpected error codes fall back to the generic state",
      "",
      "**Backend (/api/users, /api/posts)**",
      "- Missing required fields return 400 with VALIDATION_ERROR",
      "- Database failures return 503 with NETWORK_ERROR",
      "- Unhandled exceptions return 500 with UNKNOWN_ERROR",
      "- Production mode never includes stack traces in the response",
    ].join("\n"),
  },
  {
    type: "response",
    agent: "qa-engineer",
    output: [
      "Test suite complete. Added 14 test cases across two files:",
      "",
      "**src/components/__tests__/ErrorDialog.test.tsx** (6 tests)",
      "- ✅ renders 'Connection failed' for NETWORK_ERROR",
      "- ✅ renders retry button for NETWORK_ERROR, calls onRetry on click",
      "- ✅ renders 'Invalid input' for VALIDATION_ERROR",
      "- ✅ renders field-level errors when fieldErrors prop is provided",
      "- ✅ renders 'Something went wrong' for UNKNOWN_ERROR",
      "- ✅ falls back to UNKNOWN_ERROR state for unrecognized error codes",
      "",
      "**src/routes/__tests__/error-responses.test.ts** (8 tests)",
      "- ✅ POST /api/users with missing email returns 400 + VALIDATION_ERROR",
      "- ✅ POST /api/users with DB down returns 503 + NETWORK_ERROR",
      "- ✅ POST /api/users with thrown error returns 500 + UNKNOWN_ERROR",
      "- ✅ POST /api/posts with short title returns 400 + VALIDATION_ERROR",
      "- ✅ PUT /api/posts with invalid ID returns 400 + VALIDATION_ERROR",
      "- ✅ Production mode error has no stack trace in details",
      "- ✅ Development mode error includes stack trace in details",
      "- ✅ Error middleware sets correct Content-Type header",
      "",
      "All 14 tests pass. One minor finding: the UNKNOWN_ERROR state in ErrorDialog doesn't show a retry button, but the design spec doesn't mention one either — might be worth confirming with the team.",
    ].join("\n"),
  },
  {
    type: "delegation",
    from: "validation-lead",
    to: "security-rev",
    task: [
      "Security review of the new error handling implementation. Focus on:",
      "",
      "1. **Information leakage** — do any error responses expose internal paths, stack traces, or schema details in production mode?",
      "2. **Error middleware** — does src/middleware/error.ts correctly sanitize errors before sending to the client?",
      "3. **Validation errors** — the Zod validation errors are included in the response details — check if they leak type information",
      "",
      "Review these files: src/middleware/error.ts, src/routes/users.ts, src/routes/posts.ts, shared/types.ts",
    ].join("\n"),
  },
  {
    type: "response",
    agent: "security-rev",
    output: [
      "Security review complete. One finding, severity: **medium**.",
      "",
      "**✅ PASS: Error middleware (src/middleware/error.ts)**",
      "- Correctly strips stack traces in production mode",
      "- Uses generic 'Internal server error' message for unhandled exceptions",
      "- Sets appropriate HTTP status codes",
      "",
      "**✅ PASS: Route handlers**",
      "- /api/users and /api/posts don't expose internal paths",
      "- Database connection errors don't leak connection strings in production",
      "",
      "**���️ FINDING: Zod validation error leakage (src/routes/users.ts:42, posts.ts:38)**",
      "- When Zod parsing fails, the raw ZodError is spread into `details.fields`",
      "- This includes the full schema path (e.g., `body.email`), expected types (`string`), and validation messages",
      "- An attacker could enumerate the API schema by sending malformed requests",
      "- **Recommendation:** Map Zod errors to a sanitized format: `{ field: 'email', message: 'Required' }` — strip type info and schema paths",
      "",
      "**Risk:** Low-to-medium. Not exploitable for RCE, but enables API schema enumeration which aids further attacks.",
    ].join("\n"),
  },
  {
    type: "response",
    agent: "validation-lead",
    output: [
      "Validation complete. Results:",
      "",
      "**QA: PASS** — 14 test cases added, all passing. Coverage includes all three error states on both frontend and backend, plus production/development mode behavior.",
      "",
      "**Security: 1 finding (medium severity)**",
      "- Zod validation errors leak schema details (field types, paths) in the API response",
      "- Recommendation: sanitize Zod errors to only include field name + human-readable message",
      "- Not a blocker for release, but should be addressed before the next production deploy",
      "",
      "Overall the implementation is solid. The error middleware correctly handles the production/development split, and the shared type system prevents frontend/backend drift.",
    ].join("\n"),
  },
  {
    type: "response",
    agent: "orchestrator",
    output: [
      "Feature X (error handling) is complete. Here's the full status:",
      "",
      "**Engineering** ✅",
      "- Frontend: ErrorDialog component with 3 error states, ErrorBoundary for crash recovery, CSS animations",
      "- Backend: Structured ErrorResponse on all API endpoints, error middleware for unhandled exceptions",
      "- Error codes shared via shared/types.ts — single source of truth",
      "",
      "**QA** ✅",
      "- 14 test cases added and passing (6 frontend, 8 backend)",
      "- Covers all error states, field-level errors, and production/dev mode behavior",
      "",
      "**Security** ⚠️ **1 medium finding**",
      "- Zod validation errors expose schema details in the API response",
      "- Recommended fix: sanitize to `{ field, message }` format before responding",
      "- Not blocking release, flagged for follow-up before next production deploy",
      "",
      "Ready to merge pending the Zod sanitization fix.",
    ].join("\n"),
  },
];
